### ISSUE TITLE
Cleaner GUI

### ISSUE THREAD

**Issue by pepijncobben** [Zedtho/Smack#2]
Currently, the GUI kind of sucks. It's a kind of old looking tkinter window. 

A couple guiding things: 
Super fast start-up. Look nice and easy to use. Required for habitual use.
Home page should be as simple as possible.
Long-term settings (e.g. system prompt, model provider, API-key etc.) should be on a 2nd page.

A possible rough wireframe that may look nice (though I may merge system prompt with the settings page).

![image](https://github.com/user-attachments/assets/5816d8b0-f173-44bf-a2d8-b4d0ef6f121d)

**Comment by Zedtho** [comment]
b44aae2471f2d389be293728b98d58a94e3ca919 has a GUI (that isn't properly connected yet though, but has every pattern of required syntax). It can be run by simply running gui.py. I'll have to figure out how I want this to interface with the rest, though.

**Comment by Zedtho** [comment]
48661bdabb92179947d35dac60743391e3762d77 has a working GUI, for the most part. Missing is: Allow/Block website integration, and all the buttons beneath it.

**Comment by Zedtho** [comment]
148744d557f462d8a1c183ddf734945cbe7a8e52 has Allow/Block website integrated. As the further buttons beneath it are for fun, I consider this closed.

**Comment by Zedtho** [comment]
As a note, the further buttons (except Run at StartUp) are now also implemented.
